use std::{env, fs, path::Path, path::PathBuf, process::Command};

// The getters every circuit's generated code exposes and that the cxx bridge
// (src/generate.rs) consumes. Kept in sync with witness.h / generate.rs.
const GETTERS: &[&str] = &[
    "get_size_of_io_map",
    "get_total_signal_no",
    "get_main_input_signal_no",
    "get_main_input_signal_start",
    "get_number_of_components",
    "get_size_of_constants",
    "get_size_of_input_hashmap",
    "get_size_of_witness",
];

fn main() {
    if cfg!(feature = "build-witness") {
        let witness_cpp = env::var("WITNESS_CPP").unwrap();
        let library_path = env::var("CIRCOM_LIBRARY_PATH").ok();

        // WITNESS_CPP may list several circuits separated by ':'.
        let circuits: Vec<&str> = witness_cpp
            .split(':')
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .collect();
        assert!(!circuits.is_empty(), "WITNESS_CPP is empty");

        let mut names: Vec<String> = Vec::new();
        let mut cc_files: Vec<PathBuf> = Vec::new();

        for circuit in &circuits {
            let circuit_file = Path::new(circuit);
            let circuit_name = circuit_file
                .file_stem()
                .unwrap()
                .to_str()
                .unwrap()
                .to_owned();
            assert!(
                !names.contains(&circuit_name),
                "duplicate circuit name '{circuit_name}' in WITNESS_CPP"
            );

            let mut cmd = Command::new("circom");
            cmd.arg(fs::canonicalize(circuit_file).unwrap())
                .arg("--c")
                .arg("--O2");
            if let Some(ref lp) = library_path {
                cmd.arg("-l").arg(fs::canonicalize(lp).unwrap());
            }
            let status = cmd.status().unwrap();
            assert!(status.success());

            let cpp = Path::new("./")
                .join(circuit_name.clone() + "_cpp")
                .join(circuit_name.clone() + ".cpp");
            println!("cargo:warning=\"{}\"", cpp.to_str().unwrap());

            // replace.sh <cpp> <name> -> src/circuit_<name>.cc (namespaced) and
            // src/constants_<name>.dat.
            let status = Command::new("./script/replace.sh")
                .arg(cpp.to_str().unwrap())
                .arg(&circuit_name)
                .status()
                .unwrap();
            assert!(status.success());

            cc_files.push(Path::new("src").join(format!("circuit_{circuit_name}.cc")));
            names.push(circuit_name);
        }

        let out_dir = env::var("OUT_DIR").unwrap();
        let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

        // Rust registry consumed by generate.rs (included via include!).
        let mut reg = String::new();
        reg.push_str("// @generated by build.rs - circuit registry\n");
        reg.push_str("pub const CIRCUIT_NAMES: &[&str] = &[\n");
        for n in &names {
            reg.push_str(&format!("    \"{n}\",\n"));
        }
        reg.push_str("];\n\n");
        reg.push_str("pub const CIRCUIT_DATS: &[&[u8]] = &[\n");
        for n in &names {
            reg.push_str(&format!(
                "    include_bytes!(\"{manifest_dir}/src/constants_{n}.dat\"),\n"
            ));
        }
        reg.push_str("];\n");
        fs::write(Path::new(&out_dir).join("circuits.rs"), reg).unwrap();

        // C++ dispatcher: forward-declare each circuit's namespaced entry points
        // and route the global run()/get_*() to the selected circuit by index.
        let mut disp = String::new();
        disp.push_str("// @generated by build.rs - circuit dispatcher\n");
        disp.push_str("#include \"circom-witness-rs/include/witness.h\"\n\n");
        disp.push_str("struct Circom_CalcWit;\n\n");
        for n in &names {
            disp.push_str(&format!("namespace wit_{n} {{\n"));
            disp.push_str("  void run(Circom_CalcWit*);\n");
            for g in GETTERS {
                disp.push_str(&format!("  uint {g}();\n"));
            }
            disp.push_str("}\n");
        }
        disp.push('\n');
        disp.push_str("void run(Circom_CalcWit* ctx, uint32_t circuit) {\n");
        disp.push_str("  switch (circuit) {\n");
        for (i, n) in names.iter().enumerate() {
            disp.push_str(&format!("    case {i}: wit_{n}::run(ctx); return;\n"));
        }
        disp.push_str("  }\n}\n\n");
        for g in GETTERS {
            disp.push_str(&format!("uint {g}(uint32_t circuit) {{\n"));
            disp.push_str("  switch (circuit) {\n");
            for (i, n) in names.iter().enumerate() {
                disp.push_str(&format!("    case {i}: return wit_{n}::{g}();\n"));
            }
            disp.push_str("  }\n  return 0;\n}\n\n");
        }
        let disp_path = Path::new("src").join("dispatch.cc");
        fs::write(&disp_path, disp).unwrap();

        let mut build = cxx_build::bridge("src/generate.rs");
        for cc in &cc_files {
            build.file(cc);
        }
        build.file(&disp_path);
        build
            .flag_if_supported("-std=c++14")
            .flag_if_supported("-w")
            .flag_if_supported("-d")
            .flag_if_supported("-g")
            .compile("circom-witness-rs");
        
        // Regenerate when configuration is changed
        println!("cargo:rerun-if-changed=src/main.rs");
        println!("cargo:rerun-if-env-changed=WITNESS_CPP");
        println!("cargo:rerun-if-changed=include/witness.h");
        println!("cargo:rerun-if-changed=script/replace.sh");
    }
}
