#![allow(non_snake_case)]

use crate::field::{self, *};
use crate::HashSignalInfo;
use crate::{graph, M};
use byteorder::{LittleEndian, ReadBytesExt};
use ffi::InputOutputList;
use ruint::{aliases::U256, uint};
use std::{io::Read, time::Instant};

#[cxx::bridge]
mod ffi {

    #[derive(Debug, Default, Clone)]
    pub struct InputOutputList {
        pub defs: Vec<IOFieldDef>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct IOFieldDef {
        pub code: usize,
        pub offset: usize,
        pub lengths: Vec<usize>,
        pub size: u32,
        pub busId: u32,
    }

    #[derive(Debug, Default, Clone)]
    struct Circom_Component {
        templateId: u64,
        signalStart: u64,
        inputCounter: u64,
        templateName: String,
        componentName: String,
        idFather: u64,
        subcomponents: Vec<u32>,
        outputIsSet: Vec<bool>,
    }

    #[derive(Debug)]
    struct Circom_CalcWit {
        signalValues: Vec<FrElement>,
        componentMemory: Vec<Circom_Component>,
        circuitConstants: Vec<FrElement>,
        templateInsId2IOSignalInfoList: Vec<InputOutputList>,
        listOfTemplateMessages: Vec<String>,
    }

    // Rust types and signatures exposed to C++.
    extern "Rust" {
        type FrElement;

        unsafe fn bbf(
            component_name: String,
            lvarcall: &Vec<FrElement>,
            destination: *mut FrElement,
        );
        fn create_vec(len: usize) -> Vec<FrElement>;
        fn create_vec_u32(len: usize) -> Vec<u32>;
        fn generate_position_array(
            prefix: String,
            dimensions: Vec<u32>,
            size_dimensions: u32,
            index: u32,
        ) -> String;

        // Field operations
        unsafe fn Fr_mul(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_add(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_sub(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_copy(to: *mut FrElement, a: *const FrElement);
        unsafe fn Fr_copyn(to: *mut FrElement, a: *const FrElement, n: usize);
        unsafe fn Fr_neg(to: *mut FrElement, a: *const FrElement);
        unsafe fn Fr_inv(to: *mut FrElement, a: *const FrElement);
        unsafe fn Fr_div(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_mod(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        // unsafe fn Fr_square(to: *mut FrElement, a: *const FrElement);
        unsafe fn Fr_shl(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_shr(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_band(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_land(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        // fn Fr_bor(to: &mut FrElement, a: &FrElement, b: &FrElement);
        // fn Fr_bxor(to: &mut FrElement, a: &FrElement, b: &FrElement);
        // fn Fr_bnot(to: &mut FrElement, a: &FrElement);
        unsafe fn Fr_eq(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_neq(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_lt(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_gt(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_leq(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_geq(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_isTrue(a: *mut FrElement) -> bool;
        // fn Fr_fromBool(to: &mut FrElement, a: bool);
        unsafe fn Fr_toInt(a: *mut FrElement) -> u64;
        unsafe fn Fr_lor(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn print(a: *mut FrElement);
        unsafe fn Fr_pow(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
        unsafe fn Fr_idiv(to: *mut FrElement, a: *const FrElement, b: *const FrElement);
    }

    // C++ types and signatures exposed to Rust.
    // Each function takes a `circuit` index selecting which linked circuit to
    // address; the dispatcher generated by build.rs (src/dispatch.cc) routes it.
    unsafe extern "C++" {
        include!("circom-witness-rs/include/witness.h");

        unsafe fn run(ctx: *mut Circom_CalcWit, circuit: u32);
        fn get_size_of_io_map(circuit: u32) -> u32;
        fn get_total_signal_no(circuit: u32) -> u32;
        fn get_main_input_signal_no(circuit: u32) -> u32;
        fn get_main_input_signal_start(circuit: u32) -> u32;
        fn get_number_of_components(circuit: u32) -> u32;
        fn get_size_of_constants(circuit: u32) -> u32;
        fn get_size_of_input_hashmap(circuit: u32) -> u32;
        fn get_size_of_witness(circuit: u32) -> u32;
    }
}

// Generated by build.rs: CIRCUIT_NAMES and CIRCUIT_DATS (one .dat per circuit).
include!(concat!(env!("OUT_DIR"), "/circuits.rs"));

pub fn get_input_hash_map(circuit: u32, dat_bytes: &[u8]) -> Vec<HashSignalInfo> {
    let mut bytes = &dat_bytes[..(ffi::get_size_of_input_hashmap(circuit) as usize) * 24];
    let mut input_hash_map =
        vec![HashSignalInfo::default(); ffi::get_size_of_input_hashmap(circuit) as usize];
    for i in 0..ffi::get_size_of_input_hashmap(circuit) as usize {
        let hash = bytes.read_u64::<LittleEndian>().unwrap();
        let signalid = bytes.read_u64::<LittleEndian>().unwrap();
        let signalsize = bytes.read_u64::<LittleEndian>().unwrap();
        input_hash_map[i] = HashSignalInfo {
            hash,
            signalid,
            signalsize,
        };
    }
    input_hash_map
}

pub fn get_witness_to_signal(circuit: u32, dat_bytes: &[u8]) -> Vec<usize> {
    let mut bytes = &dat_bytes[(ffi::get_size_of_input_hashmap(circuit) as usize) * 24
        ..(ffi::get_size_of_input_hashmap(circuit) as usize) * 24
            + (ffi::get_size_of_witness(circuit) as usize) * 8];
    let mut signal_list = Vec::with_capacity(ffi::get_size_of_witness(circuit) as usize);
    for _ in 0..ffi::get_size_of_witness(circuit) as usize {
        signal_list.push(bytes.read_u64::<LittleEndian>().unwrap() as usize);
    }
    signal_list
}

pub fn get_constants(circuit: u32, dat_bytes: &[u8]) -> Vec<FrElement> {
    if ffi::get_size_of_constants(circuit) == 0 {
        return vec![];
    }

    // skip the first part
    let mut bytes = &dat_bytes[(ffi::get_size_of_input_hashmap(circuit) as usize) * 24
        + (ffi::get_size_of_witness(circuit) as usize) * 8..];
    let mut constants =
        vec![field::constant(U256::from(0)); ffi::get_size_of_constants(circuit) as usize];
    for i in 0..ffi::get_size_of_constants(circuit) as usize {
        let sv = bytes.read_i32::<LittleEndian>().unwrap() as i32;
        let typ = bytes.read_u32::<LittleEndian>().unwrap() as u32;

        let mut buf = [0; 32];
        bytes.read_exact(&mut buf).unwrap();

        if typ & 0x80000000 == 0 {
            let c = if sv < 0 {
                M - U256::from(sv.abs() as u32)
            } else {
                U256::from(sv as u32)
            };
            constants[i] = field::constant(c);
        } else {
            constants[i] =
                field::constant(U256::from_le_bytes(buf).mul_redc(uint!(1_U256), M, INV));
        }
    }

    return constants;
}

pub fn get_iosignals(circuit: u32, dat_bytes: &[u8]) -> Vec<InputOutputList> {
    if ffi::get_size_of_io_map(circuit) == 0 {
        return vec![];
    }

    // skip the first part
    let mut bytes = &dat_bytes[(ffi::get_size_of_input_hashmap(circuit) as usize) * 24
        + (ffi::get_size_of_witness(circuit) as usize) * 8
        + (ffi::get_size_of_constants(circuit) as usize * 40)..];
    let io_size = ffi::get_size_of_io_map(circuit) as usize;
    let hashmap_size = ffi::get_size_of_input_hashmap(circuit) as usize;
    let mut indices = vec![0usize; io_size];

    (0..io_size).for_each(|i| {
        let t32 = bytes.read_u32::<LittleEndian>().unwrap() as usize;
        indices[i] = t32;
    });

    let max_index = indices.iter().max().unwrap();
    let mut map: Vec<InputOutputList> = vec![InputOutputList::default(); *max_index + 1];

    (0..io_size).for_each(|i| {
        let l32 = bytes.read_u32::<LittleEndian>().unwrap() as usize;
        let mut io_list: InputOutputList = InputOutputList { defs: vec![] };

        (0..l32).for_each(|_j| {
            let offset = bytes.read_u32::<LittleEndian>().unwrap() as usize;
            let len = bytes.read_u32::<LittleEndian>().unwrap() as usize;

            let mut lengths = vec![0usize; len];

            (0..len).for_each(|k| {
                lengths[k] = bytes.read_u32::<LittleEndian>().unwrap() as usize;
            });

            let size = bytes.read_u32::<LittleEndian>().unwrap();
            let busId = bytes.read_u32::<LittleEndian>().unwrap();

            io_list.defs.push(ffi::IOFieldDef {
                code: 0,
                offset,
                lengths,
                size,
                busId,
            });
        });
        map[indices[i]] = io_list;
    });
    map
}

/// Run the cpp witness generator for every circuit listed in `WITNESS_CPP` and
/// optimize each graph. Writes `graph_<name>.bin` per circuit. When a single
/// circuit is configured it also writes `graph.bin` for backwards compatibility.
pub fn build_witness() -> eyre::Result<()> {
    for (circuit, name) in CIRCUIT_NAMES.iter().enumerate() {
        build_witness_for(circuit as u32, name)?;
    }
    Ok(())
}

/// Run the cpp witness generator for a single circuit
pub fn build_witness_for(circuit: u32, name: &str) -> eyre::Result<()> {
    // Reset the symbolic execution state in case a previous circuit was traced.
    field::reset_graph();

    let dat_bytes = CIRCUIT_DATS[circuit as usize];

    let mut signal_values = vec![];
    for i in 0..ffi::get_total_signal_no(circuit) as usize {
        signal_values.push(field::undefined(i));
    }
    signal_values[0] = field::constant(uint!(1_U256));

    let main_input_start = ffi::get_main_input_signal_start(circuit) as usize;
    let main_input_len = ffi::get_main_input_signal_no(circuit) as usize;

    for i in main_input_start..main_input_start + main_input_len {
        signal_values[i] = field::input(i, uint!(0_U256));
    }

    let mut ctx = ffi::Circom_CalcWit {
        signalValues: signal_values,
        componentMemory: vec![
            ffi::Circom_Component::default();
            ffi::get_number_of_components(circuit) as usize
        ],
        circuitConstants: get_constants(circuit, dat_bytes),
        templateInsId2IOSignalInfoList: get_iosignals(circuit, dat_bytes),
        listOfTemplateMessages: vec![],
    };

    // measure time
    let now = Instant::now();
    unsafe {
        ffi::run(&mut ctx as *mut _, circuit);
    }
    eprintln!("[{name}] Calculation took: {:?}", now.elapsed());

    let signal_values = get_witness_to_signal(circuit, dat_bytes);
    let mut signals = signal_values
        .into_iter()
        .map(|i| ctx.signalValues[i].0)
        .collect::<Vec<_>>();
    let mut nodes = field::get_graph();
    eprintln!("[{name}] Graph with {} nodes", nodes.len());

    // Optimize graph
    graph::optimize(&mut nodes, &mut signals);

    // Store graph to file.
    let input_map = get_input_hash_map(circuit, dat_bytes);
    let bytes = postcard::to_stdvec(&(&nodes, &signals, &input_map)).unwrap();
    eprintln!("[{name}] Graph size: {} bytes", bytes.len());
    std::fs::write(format!("graph_{name}.bin"), &bytes).unwrap();
    if CIRCUIT_NAMES.len() == 1 {
        std::fs::write("graph.bin", &bytes).unwrap();
    }

    Ok(())
}
